source 'https://github.com/ipapamagic/IPaPods.git'
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '12.0'
use_frameworks!
target 'IPaSecurity_Tests' do
  pod 'IPaSecurity', :path => '../'
  
end
